version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  disable-all: true
  disable:
    - godox
  enable:
    # Error detection
    - errcheck
    - errorlint
    - govet
    - staticcheck

    # Code quality
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - unconvert
    - unparam
    - unused
    - whitespace

    # Style and formatting
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - durationcheck
    - errname
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
  exclusions:
    rules:
      - text: "exported: exported"
        linters:
          - revive
  settings:
    lll:
      line-length: 140
    funlen:
      # Checks the number of lines in a function.
      # If lower than 0, disable the check.
      lines: 200
      # Checks the number of statements in a function.
      # If lower than 0, disable the check.
      statements: 100
      # Ignore comments when counting lines.
      # Default: true
      ignore-comments: true
    gocyclo:
      # Minimal code complexity to report.
      min-complexity: 60
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - swaggo
