version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters:
  disable-all: true
  enable:
    # Error detection
    - errcheck
    - errorlint
    - govet
    - staticcheck

    # Code quality
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - unconvert
    - unparam
    - unused
    - whitespace

    # Style and formatting
    - asciicheck
    - bidichk
    - containedctx
    - contextcheck
    - durationcheck
    - errname
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
