// Code generated by MockGen. DO NOT EDIT.
// Source: updater.go
//
// Generated by this command:
//
//	mockgen -destination mock_updater_test.go -package main -source=updater.go
//

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
	isgomock struct{}
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// GetSourceID mocks base method.
func (m *MockSource) GetSourceID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSourceID")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetSourceID indicates an expected call of GetSourceID.
func (mr *MockSourceMockRecorder) GetSourceID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSourceID", reflect.TypeOf((*MockSource)(nil).GetSourceID))
}

// GetStatusString mocks base method.
func (m *MockSource) GetStatusString() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusString")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStatusString indicates an expected call of GetStatusString.
func (mr *MockSourceMockRecorder) GetStatusString() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusString", reflect.TypeOf((*MockSource)(nil).GetStatusString))
}

// GetStringDiffWithTarget mocks base method.
func (m *MockSource) GetStringDiffWithTarget(arg0 Target) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStringDiffWithTarget", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStringDiffWithTarget indicates an expected call of GetStringDiffWithTarget.
func (mr *MockSourceMockRecorder) GetStringDiffWithTarget(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStringDiffWithTarget", reflect.TypeOf((*MockSource)(nil).GetStringDiffWithTarget), arg0)
}

// GetTargetID mocks base method.
func (m *MockSource) GetTargetID() TargetID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetID")
	ret0, _ := ret[0].(TargetID)
	return ret0
}

// GetTargetID indicates an expected call of GetTargetID.
func (mr *MockSourceMockRecorder) GetTargetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetID", reflect.TypeOf((*MockSource)(nil).GetTargetID))
}

// GetTitle mocks base method.
func (m *MockSource) GetTitle() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTitle")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTitle indicates an expected call of GetTitle.
func (mr *MockSourceMockRecorder) GetTitle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTitle", reflect.TypeOf((*MockSource)(nil).GetTitle))
}

// SameProgressWithTarget mocks base method.
func (m *MockSource) SameProgressWithTarget(arg0 Target) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SameProgressWithTarget", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SameProgressWithTarget indicates an expected call of SameProgressWithTarget.
func (mr *MockSourceMockRecorder) SameProgressWithTarget(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SameProgressWithTarget", reflect.TypeOf((*MockSource)(nil).SameProgressWithTarget), arg0)
}

// SameTitleWithTarget mocks base method.
func (m *MockSource) SameTitleWithTarget(arg0 Target) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SameTitleWithTarget", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SameTitleWithTarget indicates an expected call of SameTitleWithTarget.
func (mr *MockSourceMockRecorder) SameTitleWithTarget(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SameTitleWithTarget", reflect.TypeOf((*MockSource)(nil).SameTitleWithTarget), arg0)
}

// SameTypeWithTarget mocks base method.
func (m *MockSource) SameTypeWithTarget(arg0 Target) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SameTypeWithTarget", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SameTypeWithTarget indicates an expected call of SameTypeWithTarget.
func (mr *MockSourceMockRecorder) SameTypeWithTarget(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SameTypeWithTarget", reflect.TypeOf((*MockSource)(nil).SameTypeWithTarget), arg0)
}

// String mocks base method.
func (m *MockSource) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockSourceMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockSource)(nil).String))
}

// MockTarget is a mock of Target interface.
type MockTarget struct {
	ctrl     *gomock.Controller
	recorder *MockTargetMockRecorder
	isgomock struct{}
}

// MockTargetMockRecorder is the mock recorder for MockTarget.
type MockTargetMockRecorder struct {
	mock *MockTarget
}

// NewMockTarget creates a new mock instance.
func NewMockTarget(ctrl *gomock.Controller) *MockTarget {
	mock := &MockTarget{ctrl: ctrl}
	mock.recorder = &MockTargetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTarget) EXPECT() *MockTargetMockRecorder {
	return m.recorder
}

// GetTargetID mocks base method.
func (m *MockTarget) GetTargetID() TargetID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetID")
	ret0, _ := ret[0].(TargetID)
	return ret0
}

// GetTargetID indicates an expected call of GetTargetID.
func (mr *MockTargetMockRecorder) GetTargetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetID", reflect.TypeOf((*MockTarget)(nil).GetTargetID))
}

// GetTitle mocks base method.
func (m *MockTarget) GetTitle() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTitle")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTitle indicates an expected call of GetTitle.
func (mr *MockTargetMockRecorder) GetTitle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTitle", reflect.TypeOf((*MockTarget)(nil).GetTitle))
}

// String mocks base method.
func (m *MockTarget) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockTargetMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockTarget)(nil).String))
}
