// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination mock_service_test.go -package main -source=service.go
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMediaService is a mock of MediaService interface.
type MockMediaService struct {
	ctrl     *gomock.Controller
	recorder *MockMediaServiceMockRecorder
	isgomock struct{}
}

// MockMediaServiceMockRecorder is the mock recorder for MockMediaService.
type MockMediaServiceMockRecorder struct {
	mock *MockMediaService
}

// NewMockMediaService creates a new mock instance.
func NewMockMediaService(ctrl *gomock.Controller) *MockMediaService {
	mock := &MockMediaService{ctrl: ctrl}
	mock.recorder = &MockMediaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaService) EXPECT() *MockMediaServiceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockMediaService) GetByID(ctx context.Context, id TargetID, prefix string) (Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, prefix)
	ret0, _ := ret[0].(Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMediaServiceMockRecorder) GetByID(ctx, id, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMediaService)(nil).GetByID), ctx, id, prefix)
}

// GetByName mocks base method.
func (m *MockMediaService) GetByName(ctx context.Context, name, prefix string) ([]Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name, prefix)
	ret0, _ := ret[0].([]Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockMediaServiceMockRecorder) GetByName(ctx, name, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockMediaService)(nil).GetByName), ctx, name, prefix)
}

// Update mocks base method.
func (m *MockMediaService) Update(ctx context.Context, id TargetID, src Source, prefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, src, prefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMediaServiceMockRecorder) Update(ctx, id, src, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMediaService)(nil).Update), ctx, id, src, prefix)
}

// MockMediaServiceWithMALID is a mock of MediaServiceWithMALID interface.
type MockMediaServiceWithMALID struct {
	ctrl     *gomock.Controller
	recorder *MockMediaServiceWithMALIDMockRecorder
	isgomock struct{}
}

// MockMediaServiceWithMALIDMockRecorder is the mock recorder for MockMediaServiceWithMALID.
type MockMediaServiceWithMALIDMockRecorder struct {
	mock *MockMediaServiceWithMALID
}

// NewMockMediaServiceWithMALID creates a new mock instance.
func NewMockMediaServiceWithMALID(ctrl *gomock.Controller) *MockMediaServiceWithMALID {
	mock := &MockMediaServiceWithMALID{ctrl: ctrl}
	mock.recorder = &MockMediaServiceWithMALIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaServiceWithMALID) EXPECT() *MockMediaServiceWithMALIDMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockMediaServiceWithMALID) GetByID(ctx context.Context, id TargetID, prefix string) (Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, prefix)
	ret0, _ := ret[0].(Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMediaServiceWithMALIDMockRecorder) GetByID(ctx, id, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMediaServiceWithMALID)(nil).GetByID), ctx, id, prefix)
}

// GetByMALID mocks base method.
func (m *MockMediaServiceWithMALID) GetByMALID(ctx context.Context, malID int, prefix string) (Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMALID", ctx, malID, prefix)
	ret0, _ := ret[0].(Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMALID indicates an expected call of GetByMALID.
func (mr *MockMediaServiceWithMALIDMockRecorder) GetByMALID(ctx, malID, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMALID", reflect.TypeOf((*MockMediaServiceWithMALID)(nil).GetByMALID), ctx, malID, prefix)
}

// GetByName mocks base method.
func (m *MockMediaServiceWithMALID) GetByName(ctx context.Context, name, prefix string) ([]Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name, prefix)
	ret0, _ := ret[0].([]Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockMediaServiceWithMALIDMockRecorder) GetByName(ctx, name, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockMediaServiceWithMALID)(nil).GetByName), ctx, name, prefix)
}

// Update mocks base method.
func (m *MockMediaServiceWithMALID) Update(ctx context.Context, id TargetID, src Source, prefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, src, prefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMediaServiceWithMALIDMockRecorder) Update(ctx, id, src, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMediaServiceWithMALID)(nil).Update), ctx, id, src, prefix)
}
