// Code generated by MockGen. DO NOT EDIT.
// Source: strategies.go
//
// Generated by this command:
//
//	mockgen -destination mock_strategy_test.go -package main -source=strategies.go
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTargetFindStrategy is a mock of TargetFindStrategy interface.
type MockTargetFindStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockTargetFindStrategyMockRecorder
	isgomock struct{}
}

// MockTargetFindStrategyMockRecorder is the mock recorder for MockTargetFindStrategy.
type MockTargetFindStrategyMockRecorder struct {
	mock *MockTargetFindStrategy
}

// NewMockTargetFindStrategy creates a new mock instance.
func NewMockTargetFindStrategy(ctrl *gomock.Controller) *MockTargetFindStrategy {
	mock := &MockTargetFindStrategy{ctrl: ctrl}
	mock.recorder = &MockTargetFindStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetFindStrategy) EXPECT() *MockTargetFindStrategyMockRecorder {
	return m.recorder
}

// FindTarget mocks base method.
func (m *MockTargetFindStrategy) FindTarget(ctx context.Context, src Source, existingTargets map[TargetID]Target, prefix string, report *SyncReport) (Target, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTarget", ctx, src, existingTargets, prefix, report)
	ret0, _ := ret[0].(Target)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindTarget indicates an expected call of FindTarget.
func (mr *MockTargetFindStrategyMockRecorder) FindTarget(ctx, src, existingTargets, prefix, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTarget", reflect.TypeOf((*MockTargetFindStrategy)(nil).FindTarget), ctx, src, existingTargets, prefix, report)
}

// Name mocks base method.
func (m *MockTargetFindStrategy) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockTargetFindStrategyMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockTargetFindStrategy)(nil).Name))
}
