name: golangci-lint

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "**.md"
      - "doc/**"
      - ".vscode/**"
      - ".idea/**"
      - "examples/**"
      - "docker-compose.yml"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    paths-ignore:
      - "**.md"
      - "doc/**"
      - ".vscode/**"
      - ".idea/**"
      - "examples/**"
      - "docker-compose.yml"
      - "LICENSE"
      - ".gitignore"

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: "1.25"
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: v2.10.1
          only-new-issues: true
